### ISSUE TITLE
diapos

### ISSUE THREAD

**Issue by montoyamoraga** [gamontec/projects#1]
por Guillermo Montecinos, miembro de Coded - Escuela de artes mediales 
https://www.facebook.com/codedEscuela/ he ahi el link

- montoya-moraga por favor, porque asi hago todo para diferenciarme de los otros doscientos personas con mi nombre. reemplazar oyarzú por oyarzún.

- bibliotecas, en vez de librerías.

- JavaScript en vez de .js

- paréntesis, llaves y corchetes.

- la última diapo deberia ser la misma que la primera o no?

**Comment by gamontec** [comment]
Hice todas las modificaciones, excepto el punto que dice "paréntesis, llaves y corchetes." porque no entendí a qué se refiere.

**Comment by montoyamoraga** [comment]
en una parte dice "paréntesis de corchete", digo que lo reemplaces por "paréntesis, llaves y corchetes", porque esos son los nombres, y cada uno tiene usos distintos en JS.
